#:schema node_modules/wrangler/config-schema.json
name = "unicornsurf"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[build]
command = "NODE_VERSION=18.17.1 PNPM_VERSION=9.4.0 ./build.sh"
publish = "./build/client"

[build.environment_variables]
NODE_VERSION = "18.17.1"
PNPM_VERSION = "9.4.0"
NODE_OPTIONS = "--max-old-space-size=4096"

[env.production]
compatibility_flags = ["nodejs_compat"]
