#:schema node_modules/wrangler/config-schema.json
name = "unicornsurf"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[env.production]
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
publish = "./build/client"
